In [3]:
import pandas as pd
import numpy as np
from ta.volatility import AverageTrueRange
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

In [ ]:
FUTURES_NAME = "Si"
START_DATE = "230101"
END_DATE = "241031"

In [5]:
df_daily = pd.read_csv(f"../src/daily_data/{FUTURES_NAME}_{START_DATE}_{END_DATE}.csv", sep=";")
df_min = pd.read_excel("../src/stock_data.xlsx", sheet_name=FUTURES_NAME)

In [6]:
def prepare_df(df: pd.DataFrame):
    df = df.rename(columns={col: col.replace("<", "").replace(">", "") for col in df.columns})
    df.drop(["TICKER", "PER"], axis=1, inplace=True)
    df["DATE"] = pd.to_datetime(df["DATE"], format="%y%m%d")
    return df

In [7]:
def get_atr(data, window=14):
    atr = AverageTrueRange(
        high=data["HIGH"],
        low=data["LOW"],
        close=data["CLOSE"],
        window=window
    ).average_true_range()
    return atr

In [8]:
df_daily = prepare_df(df_daily)
df_min = prepare_df(df_min)

In [9]:
myatr = get_atr(df_daily)
df_daily["ATR"] = round(myatr, 2)

In [10]:
df_daily.head(3)

        DATE  TIME   OPEN   HIGH    LOW  CLOSE    VOL  ATR
0 2023-01-03     0  72720  74832  72268  74796  83305  0.0
1 2023-01-04     0  74677  75442  74082  75401  58521  0.0
2 2023-01-05     0  75391  75775  74529  75282  48062  0.0

In [11]:
df_daily = df_daily.loc[df_daily["ATR"] > 0]

In [12]:
df_daily["CANDLE_COLOR"] = np.where(df_daily["CLOSE"] > df_daily["OPEN"], 1, 0)
df_daily["PREV_CANDLE_COLOR"] = df_daily["CANDLE_COLOR"].shift()

In [13]:
df_daily["SL_SIZE"] = round(df_daily["ATR"] / 3, 0)
df_daily["TP_SIZE"] = round(df_daily["ATR"] * 2 / 3, 0)

for col in ["SL_SIZE", "TP_SIZE"]:
    df_daily[col] = df_daily[col].shift()

In [14]:
df_daily = df_daily.dropna()

In [15]:
df_min = df_min.merge(df_daily[[
    "DATE",
    "ATR",
    "PREV_CANDLE_COLOR",
    "SL_SIZE",
    "TP_SIZE",
    # "LONG_SL",
    # "LONG_TP",
    # "SHORT_SL",
    # "SHORT_TP"
]], how="left", on="DATE")

In [16]:
df_min = df_min.dropna()

In [17]:
df_daily["PROFIT_LONG"] = 0
df_daily["PROFIT_SHORT"] = 0

In [18]:
df_daily = df_daily.loc[df_daily["DATE"].isin(df_min["DATE"].unique())]
df_min = df_min.loc[df_min["DATE"].isin(df_daily["DATE"].unique())]

In [19]:
df_min.head()

,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL,ATR,PREV_CANDLE_COLOR,SL_SIZE,TP_SIZE
2402,2023-01-23,90000,74447,74750,74447,74549,1176,1303.61,1.0,443.0,886.0
2403,2023-01-23,90500,74549,74597,74549,74553,188,1303.61,1.0,443.0,886.0
2404,2023-01-23,91000,74552,74574,74498,74525,432,1303.61,1.0,443.0,886.0
2405,2023-01-23,91500,74497,74510,74327,74349,530,1303.61,1.0,443.0,886.0
2406,2023-01-23,92000,74347,74391,74330,74343,424,1303.61,1.0,443.0,886.0

In [20]:
dates = df_min["DATE"].unique()
entry_time_id = 1

for d in tqdm(dates):
    # минимальное время в дату
    min_time = df_min.loc[df_min["DATE"] == d, "TIME"].min()
    # считаем построчно срабатывание TP ил SL лонга
    df_day = df_min.loc[df_min["DATE"] == d].copy()
    for i in range(0, len(df_day)):
        entry_price = np.array(df_day["OPEN"])[entry_time_id]
        tp_long = entry_price + np.array(df_day["TP_SIZE"])[0]
        sl_long = entry_price - np.array(df_day["SL_SIZE"])[0]
        tp_short = entry_price - np.array(df_day["TP_SIZE"])[0]
        sl_short = entry_price + np.array(df_day["TP_SIZE"])[0]

        if np.array(df_day["PREV_CANDLE_COLOR"])[0] == 1:  # лонг

            if np.array(df_day["HIGH"])[i] >= tp_long:
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_LONG"] = np.array(df_day["TP_SIZE"])[0]
            elif np.array(df_day["LOW"])[i] <= sl_long:
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_LONG"] = np.array(df_day["SL_SIZE"])[0]

            # если не сработали триггеры
            else:
                profit = np.array(df_day.loc[df_day["TIME"] == 230000, "CLOSE"])[0] - entry_price
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_LONG"] = profit
        else:
            # то же самое по шорту
            if np.array(df_day["LOW"])[i] <= tp_short:
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_SHORT"] = np.array(df_day["TP_SIZE"])[0]
            elif np.array(df_day["HIGH"])[i] >= sl_short:
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_SHORT"] = np.array(df_day["SL_SIZE"])[0]
            # если не сработали триггеры
            else:
                profit = entry_price - np.array(df_day.loc[df_day["TIME"] == 230000, "CLOSE"])[0]
                df_daily.loc[df_daily["DATE"] == d, "PROFIT_SHORT"] = profit

  5%|▍         | 21/453 [00:03<01:20,  5.37it/s]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
df_daily

In [ ]:
df_daily["TOTAL_PROFIT"] = df_daily["PROFIT_LONG"] + df_daily["PROFIT_SHORT"]

In [ ]:
(df_daily["TOTAL_PROFIT"].sum()) - (10 * len(df_daily))
# 78.3% по предыдущей свече. +235186
# 147364
# 400-800 - 143745

In [ ]:
len(df_daily.loc[df_daily["TOTAL_PROFIT"] > 0]) / len(df_daily)

In [ ]:
"""
SL-TP    | PROFIT | WINRATE
-----------------------------
400-800  | 96916  | 70.7%
-----------------------------
500-1000 | 92490  | 66.0%
-----------------------------
200-400  | 81473  | 85.1%
-----------------------------
200-600  | 89927  | 81.2%
-----------------------------
200-700  | 86691  | 77.9%
-----------------------------
1/3 ATR - ATR | 82830 | 65.1%
-----------------------------
"""

In [ ]:
"""
ID | TIME  | PROFIT | WINRATE
-----------------------------
0  | 90000  | 98293 | 70.5%
-----------------------------
1  | 90500  | 85733 | 69.3%
-----------------------------
2  | 91000  | 84756 | 68.8%
-----------------------------
3  | 91500  | 83067 | 67.4%
-----------------------------
4  | 92000  | 92632 | 70.2%
-----------------------------
5  | 92500  | 82453 | 67.2%
-----------------------------
6  | 93000  | 81993 | 67.2%
-----------------------------
7  | 93500  | 87747 | 69.0%
-----------------------------
8  | 94000  | 88906 | 69.3%
-----------------------------
9  | 94500  | 89717 | 68.8%
-----------------------------
10 | 95000  | 85464 | 68.6%
-----------------------------
11 | 95500  | 84309 | 68.1%
-----------------------------
12 | 100000 | 83064 | 68.4%
-----------------------------
13 | 100500 | 85362 | 69.0%
-----------------------------
14 | 101000 | 86164 | 68.1%
-----------------------------
15 | 101500 | 89584 | 70.0%
-----------------------------
16 | 102000 | 90173 | 70.2%
-----------------------------
17 | 102500 | 87869 | 69.8%
-----------------------------
18 | 103000 | 84398 | 67.7%
-----------------------------
19 | 103500 | 81340 | 67.4%
-----------------------------
20 | 104000 | 82685 | 67.9%
-----------------------------
"""

In [ ]:
df_daily.to_excel(f"results_by_follow_{FUTURES_NAME}.xlsx")